<?php

/**
 * Created by PhpStorm.
 * User: Yangjiecheng
 * Date: 2019/8/28 0028
 * Time: 下午 14:35
 */

namespace jcore\iSecureCenter;

use yii\helpers\Json;
use yii\httpclient\Client;
use yii\httpclient\RequestEvent;

class ArtemisHttpClient extends Client
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->on(self::EVENT_BEFORE_SEND, function (RequestEvent $event) {
            $request = $event->request;
            if (!empty($request->getData())) {
                $data = is_array($request->getData()) ? Json::encode($request->getData()) : $request->getData();
                $contentMd5 = base64_encode(md5($data));
            } elseif (!empty($request->getContent())) {
                $contentMd5 = base64_encode(md5($request->getContent()));
            }

            $httpHeaders = [
                'Http Method' => strtoupper($request->getMethod()),
                'Accept' => '*/*',
                'Content-MD5' => $contentMd5,
                'Date' => date('Y-m-d H:i:s')
            ];
            $request->addHeaders($httpHeaders);
            $headers = $request->getHeaders();
            $secret = $headers['X-Ca-Secret'];
            $url = $headers['X-Ca-Url'];
            unset($headers['X-Ca-Secret'], $headers['X-Ca-Url']);
            $headerString = $this->getHeaderFormat($headers);
            $string = $headerString . $url;
            $signature = base64_encode(hash_hmac('sha256', $string, $secret, true));
            $headers['X-Ca-Signature'] = $signature;
            $request->setHeaders($headers);
        });
//        $this->on(self::EVENT_AFTER_SEND, function (RequestEvent $event) {
//            $data = $event->response->getData();
//
//            $data['content'] = base64_decode($data['encoded_content']);
//
//            $event->response->setData($data);
//        });
    }

    private function getHeaderFormat($headers)
    {
        return $headers['Http Method'] . "\n"
            . $headers['Accept'] . "\n"
            . $headers['Content-MD5'] . "\n"
            . $headers['Content-Type'] . "\n"
            . $headers['Date'] . "\n"
            . "\n";
    }
}